### ISSUE TITLE
reading meta data takes forever after update to macOS Mojave

### ISSUE THREAD

**Issue by britiscurious** [abentele/PhotosExporter#1]
After the update to macOS Mojave (which also brings Photos 4) reading meta data takes forever.

(Otherwise I really like your project because it allows me to sync the photos to an folder structure on my NAS.)

**Comment by abentele** [comment]
Unfortunatley, after investigating a little bit on this issue, I've seen the macOS API to get the Photos library has been removed by Apple. The used API was MLMediaLibrary, and as you can see on https://developer.apple.com/documentation/medialibrary/mlmediasourcetype, the supported media source types don't include the Photos library any more. Same here: https://developer.apple.com/documentation/medialibrary/mlmedialibrary/media_source_identifiers. In High Sierra there was a constant for it that still exists but isn't documented: https://developer.apple.com/documentation/medialibrary/mlmediasourcephotosidentifier. Apple themselves provided a code sample to access the Photos library, but it's not up-to-date: https://developer.apple.com/library/archive/samplecode/MediaLibraryLoader/Introduction/Intro.html#//apple_ref/doc/uid/TP40017375. It seems that Apple has removed support to read from the Photos library for third party apps.

So, currently I see no simple solution for this issue. I will further investigate on it the next days, because the PhotosExporter has become a very important tool for me, with no alternative.

**Comment by abentele** [comment]
I've opened a bug ticket in the Apple Bug tracker, #44856328. Hope to get an answer if there is any alternative API.

**Comment by britiscurious** [comment]
Thanks for the investigation. My thoughts were in the direction that eventually the new hardened Mojave security were responsible. I changed the options for
`self.mediaLibrary = MLMediaLibrary(options: options)`
to
`[:]`
in order to get all mediasources.
The only one I get is iTunes. :-(
So far I store all my photos on a NAS using a folder structer by date.
That way all devices Windows, Mac, DLNA,... are able to show the photos and backup to an arbitrary cloud storage provider is easy.

I didn't want to trap my photos within Photos and iCloud.
But PhotosExporter gave me the opportunity to use Photos and sync it to my NAS.

I really miss Aperture. Lightroom is just to expensive for my needs and there is currently no other DAM that fulfills my needs. Eagerly waiting for Affinity DAM... but still there is nothing on the horizon...

**Comment by abentele** [comment]
This is the same I've already tried. The Photos framework aka PhotoKit doesn't contain an API for retrieving photos on the Mac. I assume Apple doesn't support it on the Mac because of the implementation is not ready for features like iCloud Photos or for security reasons.

So we will have to wait for a new API from Apple, maybe forever. In the meantime, we could access the Photos Library's sqlite database to get the relevant meta data to export the photos. This would be a hack, and its likely that Apple will also remove this "backdoor" in the future.

**Comment by abentele** [comment]
Apple has closed my bug ticket as duplikate of ticket 44792418, which is currently in status Open.

**Comment by abentele** [comment]
fixed with commit 0804b65442e198cb2cfecaaeaf2486dc68db792f

As @britiscurious suspected, the access to the Photos Library is more restricted in macOS Mojave.
After this fix, the application should work both with High Sierra and Mojave.
In Mojave, the user will be asked if he wants to grant the privilege to access the Photos Library when starting the application for the first time (this decision can be changed in the System preferences/Security/Privacy panel of Mojave).

If you are already using the application, you have to rename your main.swift file to MainExporter.swift and refactor it's content like in commit 0804b65442e198cb2cfecaaeaf2486dc68db792f (encapsulate it's content in a function named export() ).

The fix consists of:
* Switch from command line to Cocoa Application (required); the application doesn't show any main window, to simulate a headless command line tool
* Info.plist with NSPhotoLibraryUsageDescription entry
