### ISSUE TITLE
Burst photos are not exported

### ISSUE THREAD

**Issue by britiscurious** [abentele/PhotosExporter#3]
Unfortunately only the main photo of a burst series is exported.
Actually those "burst series main photos" are the only MLMediaObjects that are returned when looping through e.g. the root media group. All other photos from a burst series are somehow hidden.
Examining "burst series main photos" I also could not find any attributes that point to the other photos of the burst series.

So still we have no complete solution to export all photos from Photos to extern.
It annoys me that the photos are kind of trapped in this proprietary application.

**Comment by abentele** [comment]
First of all, for me it's no real problem, because I don't use such stacked burst series at all - I mostly use my DSLR, and every photo it takes is a unique photo in the Photos app, even if I take a burst series of photos. But you are right: for example the iPhone can take burst series that are stacked in the Photos App.

I think these burst series are intended to be used in a different way: you can open the series in Photos and select some of your favorites of the series to work with. After this step, the favorites are individual photos, and they are exported as individual photos with PhotosExporter. The other photos of the stack are simply ignored when exporting the photos. This is what I would expect. The MLMediaLibrary API works according to this.

See https://www.picbackman.com/tips-tricks/how-to-view-photo-bursts-and-select-shots-to-work-in-photos-app/ for more information about how to select favorites from a burst series.

If you don't agree with me, accept it as a workaround - it's the way the Photos app works, you may love or hate it. Another option is to open a feature request / bug ticket in the Apple bug tracker.

Because I will not change anything in my application related to this issue, I close this issue.
