### ISSUE TITLE
How to create a executable and run it in crontab

### ISSUE THREAD

**Issue by synox** [abentele/PhotosExporter#5]
It works great and fast for me in Xcode. I would like to schedule it for daily runs with plist or crontab.

It would be great if you could document how to export an app binary and how to run it from command line. 

(I don't usually do swift projects, so I'm a bit lost here.)

**Comment by abentele** [comment]
Because I'm working on extending the app with a preferences dialog and automatic scheduling, which means you will not need something like cron to schedule your export tasks any more, I don't want to spend any effort in additional documentation of the current software.

Look into the https://github.com/photossync/PhotosSync if you are interested in the current status of the project.

Nevertheless a short description:
- open the project in Xcode
- press command-B to build the project
- in the left panel, open the "Products", then the context menu of "PhotosSync.app" -> "Show in Finder"
- there should be many tutorials in the web which describe how to add such an app to the crontab
